### ISSUE TITLE
ListedLoans documentation

### ISSUE THREAD

**Issue by kuhnrl30** [kuhnrl30/LendingClub#7]
@Return isn't processing correctly.

**Comment by Predacity** [comment]
Ryan, I used your code.  It works.  Thank you.  But the order submission is slow if you can only send 1 loan ID at a time.  Is there a way to send a bundle of orders in one line of code?

**Comment by kuhnrl30** [comment]
I haven't tested this yet but you should be able to pass vectors of IDs and amounts.  
```
ID_vector  <- c("loanID_1","loanID_2","loanID_3")
Amt_vector <- c( 25, 50, 25)
SubmitOrder(loanId = ID_vector, amount = Amt_vector)`
```

**Comment by Predacity** [comment]
That didn't work for me, but it is possible that it didn't work because I didn't have the cash to invest in all the loans in the order.  It seems like it is an all or nothing order, which does not allow for partial fulfillment of a few orders until you run out of cash.  Not sure if that restriction is your package or LC frankly.  The reason I am guessing this issue is cash related is because it is not giving me any error but my cash is not declining and LC is not sending me an email confirming my order.  The only thing that is working is if I do this.
SubmitOrder(ListedLoansDF$id[1], 25)
SubmitOrder(ListedLoansDF$id[2], 25)
SubmitOrder(ListedLoansDF$id[3], 25)
SubmitOrder(ListedLoansDF$id[4], 25)
SubmitOrder(ListedLoansDF$id[5], 25)
and so forth...

This treats the orders individually, and if I have the cash, executes it.  So if the ListedLoansDF had only 3 loans, then by the time it hits SubmitOrder(ListedLoansDF$id[4], 25) it will fail.  Which is okay.  And If I don't have any cash by, say, the 2nd loan, I will just not get an email from Lending Club on the 2nd loan and going forward.

While this line by line format is not that efficient, it solves the "cash sufficiency to order amount" problem.  If you can figure out how to get it to work so 1 order with many loans is not all or nothing, let me know.

**Comment by kuhnrl30** [comment]
I looked at how the request is being sent to the server and it matches the format per LC's documentation.  It looks to be well-formatted which is why you weren't getting the error.  I think the error is not the format of the request but may be in the loans you are trying to buy.  

I enhanced the response handler so you can get feedback after submitting an order without waiting for LC's email confirmation.  The new 'quiet' param is a switch determining if you get the feedback. Pass TRUE for quiet execution i.e. no feedback; pass FALSE to get the feedback.  The output will be a dataframe of loan IDs and the execution status for each.  This execution status may help determine why the order isn't posting.

Can you try again using the dev version?
```
devtools::install_github("kuhnrl30/LendingClub")
SubmitOrder(loanId = ID_vector, amount = Amt_vector, quiet=F)
```
