### ISSUE TITLE
Failed order with no error response/feedback

### ISSUE THREAD

**Issue by kuhnrl30** [kuhnrl30/LendingClub#8]
Can submit an order that does not post but user doesn't get an error.  Request is likely well-formed, but LC is blocking the purchase.  Need to build a feedback mechanism so you know why an order did or did not go through.

**Comment by kuhnrl30** [comment]
#7

**Comment by Predacity** [comment]
Excellent enhancement.  I have 26 dollars in cash.  I submitted the bundle order for 4 loans, each 25 dollars, but none of the loans were invested due to "insufficient_cash" (see table below).   I will work on improving my code to reduce the number of loans in my order based on the cash in my account.

     loanId requested / Amount / investedAmount  / executionStatus
1 107######      /        25        /      0 / INSUFFICIENT_CASH
2 107######       /       25        /      0 / INSUFFICIENT_CASH
3 107######      /        25      /        0 / INSUFFICIENT_CASH
4 107######       /       25        /      0 / INSUFFICIENT_CASH
